name: Build and Test
on:
  push:
    branches:
      - ci_pipe

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends build-essential cmake libjsoncpp-dev libzmqpp-dev libtclap-dev wget libopenmpi-dev
          wget --no-check-certificate https://www.xilinx.com/bin/public/openDownload?filename=xrt_202220.2.14.354_20.04-amd64-xrt.deb -O xrt.deb
          sudo dpgk -i xrt.deb
          sudo apt --fix-broken install -y --no-install-recommends 
      - name: Build Emulator
        run: |
          cd ${{ github.workspace }}/test/model/emulator && cmake . && make
      - name: Build Test
        run: |
          source /opt/xilinx/xrt/setup.sh
          cd ${{ github.workspace }}/test/host/xrt && cmake . && make
